# Generated by Django 2.1.3 on 2018-11-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinate',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=1000),
        ),
    ]
